// action - customization reducer
export const SET_USER = "@customization/SET_USER";
export const SET_AUTH = "@customization/SET_AUTH";

export const SET_SEARCH_TERM = "@customization/SET_SEARCH_TERM";
export const SET_FILTER_TERM = "@customization/SET_FILTER_TERM";
export const SET_ARTISTS = "@customization/SET_ARTISTS";
export const SET_ARTIST_FILTER = "@customization/SET_ARTIST_FILTER";
export const SET_LANGUAGE_FILTER = "@customization/SET_LANGUAGE_FILTER";
export const SET_ALL_USERS = "@customization/SET_ALL_USERS";
export const SET_ALL_SONGS = "@customization/SET_ALL_SONGS";
export const SET_ALL_ALBUMS = "@customization/SET_ALL_ALBUMS";
export const SET_ALBUM_FILTER = "@customization/SET_ALBUM_FILTER";
export const SET_SONG = "@customization/SET_SONG";
export const SET_SONG_PLAYING = "@customization/SET_SONG_PLAYING";
export const SET_MINI_PLAYER = "@customization/v";
export const SET_ALL_CATEGORIES = "@customization/SET_ALL_CATEGORIES";
export const SET_CATEGORY_FILTER = "@customization/SET_ALBUM_FILTER";
export const SET_ALL_ARTISTS = "@customization/SET_ALL_ARTISTS";
